name: Check Deployment Age for Specific Environment

on:
  workflow_dispatch:

jobs:
  check-deployment-age:
    runs-on: ubuntu-latest
    steps:
      - name: Check deployment age
        id: check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          REPO="${{ github.repository }}"
          echo "REPO info is $REPO"

          DEPLOYMENTS=$(gh api repos/$REPO/deployments \
            --jq '[.[] ]')
          echo "DEPLOYMENTS info is $DEPLOYMENTS"
