name: Check Deployment Age for Specific Environment

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:

jobs:
  check-deployment-age:
    runs-on: ubuntu-latest
    steps:
      - name: Check deployment age
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ENVIRONMENT: "production"         # Change to your environment
          BRANCH: "refs/heads/main"                    # Change to your branch
        run: |
          REPO="${{ github.repository }}"

          # Get deployments for the environment
          # DEPLOYMENTS=$(gh api repos/$REPO/deployments \
          #   --jq '[.[] | select(.environment == env.ENVIRONMENT and .ref == env.BRANCH)]')
          DEPLOYMENTS=$(gh api repos/$REPO/deployments \
            --jq '[.[0] | select(.environment == env.ENVIRONMENT and .ref== env.BRANCH)]')
          echo "DEPLOYMENTS info is $DEPLOYMENTS"
          if [ "$(echo "$DEPLOYMENTS" | jq length)" -eq 0 ]; then
            echo "No deployments found for environment '$ENVIRONMENT' and branch '$BRANCH'."
            exit 0
          fi

          # Loop through deployments to find the latest successful one
          for row in $(echo "$DEPLOYMENTS" | jq -r '.[] | @base64'); do
            _jq() {
              echo "${row}" | base64 --decode | jq -r "${1}"
            }

            DEPLOYMENT_ID=$(_jq '.id')
            CREATED_AT=$(_jq '.created_at')

            # Check deployment status
            STATUS=$(gh api repos/$REPO/deployments/$DEPLOYMENT_ID/statuses --jq '.[0].state')

            if [ "$STATUS" == "success" ]; then
              CREATED_DATE=$(date -d "$CREATED_AT" +%s)
              NOW=$(date +%s)
              AGE_DAYS=$(( (NOW - CREATED_DATE) / 86400 ))

              echo "Latest successful deployment is $AGE_DAYS days old."

              if [ "$AGE_DAYS" -gt 90 ]; then
                echo "Deployment is older than 90 days!"
                gh issue create --title "Deployment is older than 90 days" \
                  --body "The latest successful deployment to '$ENVIRONMENT' from branch '$BRANCH' is $AGE_DAYS days old."
              fi
              break
            fi
          done
