name: Check Deployment Age

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:     # Allows manual triggering

jobs:
  check-deployment-age:
    runs-on: ubuntu-latest
    steps:
      - name: Check latest deployment age
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          REPO="${{ github.repository }}"
          DEPLOYMENT=$(gh api repos/$REPO/deployments --jq '.[0]')
          CREATED_AT=$(echo "$DEPLOYMENT" | jq -r '.created_at')
          CREATED_DATE=$(date -d "$CREATED_AT" +%s)
          NOW=$(date +%s)
          AGE_DAYS=$(( (NOW - CREATED_DATE) / 86400 ))

          echo "Deployment age: $AGE_DAYS days"

          if [ "$AGE_DAYS" -gt 90 ]; then
            echo "Deployment is older than 90 days!"
            # Send notification (e.g., Slack, email, GitHub issue)
            # Example: create an issue
            gh issue create --title "Deployment is older than 90 days" --body "The latest deployment is $AGE_DAYS days old. Please review."
          fi
